services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/sh -c "python3 src/database_operations.py && streamlit run src/app.py --server.fileWatcherType poll"